app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', ['as'=>'home.index','uses'=>'WelcomeController@index']);
Route::get('/event', function(){
    $response = Event::fire(new \App\Events\MessageWasCreated(
        App\Models\User::find(2),
        App\Models\User::find(37)
    ));
});
Route::get('/event', function(){
    $response = Event::fire(new \App\Events\MessageWasCreated(
        App\Models\User::find(2),
        App\Models\User::find(37)
    ));
});

//login and logout are shared for administrator, wifi manager and admin
Route::get('login', array('as' => 'login.index', 'uses' => 'LoginController@index'));
Route::post('login', array('as' => 'login.authenticate', 'uses' => 'LoginController@authenticate'));
Route::get('lockout', array('as' => 'login.lockOut', 'uses' => 'LoginController@lockOut'));

//2 factor auth
Route::get('login/tfa', array('as' => 'login.show2Fa', 'uses' => 'LoginController@show2Fa'));
Route::post('login/tfa', array('as' => 'login.postProcess2Fa', 'uses' => 'LoginController@postProcess2Fa'));

//password reset link request
Route::get('password/reset/', array('as' => 'login.getEmail', 'uses' => 'LoginController@getEmail'));
Route::post('password/reset/', array('as' => 'login.postEmail', 'uses' => 'LoginController@postEmail'));

//password reset form
Route::get('password/reset/{token}', array('as' => 'login.getReset', 'uses' => 'LoginController@getReset'));
Route::post('password/reset/{token}', array('as' => 'login.postReset', 'uses' => 'LoginController@postReset'));

Route::get('logout', array('as' => 'login.logout', 'uses' => 'LoginController@logout','middleware' => 'auth'));

Route::group(array('namespace' => 'User','middleware' => 'auth'), function()
{
    // Notice how, by nesting route groups, the namespace will automatically
    // be nested as well!

    Route::match(['get','post'],'user/register',array('as'=>'user.register.index','uses'=>'RegisterController@index'));

    //dashboards
    Route::get('user/dashboard', array('as' => 'user.dashboard.index', 'uses' => 'DashboardController@index'));
    Route::get('user/settings', array('as' => 'user.dashboard.getSettings', 'uses' => 'DashboardController@getSettings'));
    Route::post('user/settings', array('as' => 'user.dashboard.postSettings', 'uses' => 'DashboardController@postSettings'));
    Route::get('user/statistics', array('as' => 'user.dashboard.getStatistics', 'uses' => 'DashboardController@getStatistics'));

    //support
    Route::get('user/support/ticket/new', array('as' => 'user.support.getNewTicket', 'uses' => 'SupportController@getNewTicket'));
    Route::post('user/support/ticket/new', array('as' => 'manager.support.postNewTicket', 'uses' => 'SupportController@postNewTicket'));
    Route::get('user/support/ticket/{id}', array('as' => 'user.support.getTickets', 'uses' => 'SupportController@getTickets'));
    Route::post('user/support/ticket/{id}', array('as' => 'user.support.postAllTickets', 'uses' => 'SupportController@postTickets'));
    Route::get('user/support/ticket/view/{id}', array('as' => 'user.support.getViewTicket', 'uses' => 'SupportController@getViewTicket'));
    Route::post('user/support/ticket/view/{id}', array('as' => 'user.support.postViewTicket', 'uses' => 'SupportController@postViewTicket'));

    //guest
    Route::get('user/guest/view', array('as' => 'user.guest.view', 'uses' => 'GuestController@view'));
    Route::post('user/guest/settings', array('as' => 'user.guest.postSettings', 'uses' => 'GuestController@postSettings'));
    Route::get('user/guest/settings', array('as' => 'user.guest.settings', 'uses' => 'GuestController@settings'));

});

Route::group(array('namespace' => 'Manager','middleware' => 'auth'), function(){

    //index
    Route::get('manager/dashboard',array('as'=>'manager.dashboard.index','uses'=>'DashboardController@index'));

    //settings
    Route::get('manager/settings', array('as' => 'manager.dashboard.getSettings', 'uses' => 'DashboardController@getSettings'));
    Route::post('manager/settings', array('as' => 'manager.dashboard.postSettings', 'uses' => 'DashboardController@postSettings'));

    //billing
    Route::get('manager/billing/invoices', array('as' => 'manager.billing.getInvoices', 'uses' => 'BillingController@getInvoices'));
    Route::post('manager/billing/invoices', array('as' => 'manager.billing.postInvoices', 'uses' => 'BillingController@postInvoices'));
    Route::get('manager/billing/subscription', array('as' => 'manager.billing.getSubscription', 'uses' => 'BillingController@getSubscription'));
    Route::post('manager/billing/subscription', array('as' => 'manager.billing.postSubscription', 'uses' => 'BillingController@postSubscription'));
    Route::get('manager/billing/invoice/{id}', array('as' => 'manager.billing.getInvoice', 'uses' => 'BillingController@getInvoice'));
    Route::post('manager/billing/invoice/{id}', array('as' => 'manager.billing.postInvoice', 'uses' => 'BillingController@postInvoice'));

    //user account
    Route::get('manager/user/package/add', array('as' => 'manager.package.getNew', 'uses' => 'PackageController@getNew'));
    Route::post('manager/user/package/add', array('as' => 'manager.package.postNew', 'uses' => 'PackageController@postNew'));
    Route::post('manager/user/package/delete', array('as' => 'manager.package.postDelete', 'uses' => 'PackageController@postDelete'));
    Route::get('manager/user/packages', array('as' => 'manager.package.getList', 'uses' => 'PackageController@getList'));
    Route::get('manager/user/package/edit/{id}', array('as' => 'manager.package.getEdit', 'uses' => 'PackageController@getEdit'));
    Route::post('manager/user/package/edit/{id}', array('as' => 'manager.package.postEdit', 'uses' => 'PackageController@postEdit'));
    Route::get('manager/user/register', array('as' => 'manager.user.getRegister', 'uses' => 'UserController@getRegister'));
    Route::post('manager/user/register', array('as' => 'manager.user.postRegister', 'uses' => 'UserController@postRegister'));
    Route::get('manager/user/edit/{id}', array('as' => 'manager.user.getEdit', 'uses' => 'UserController@getEdit'));
    Route::get('manager/user/edit/{id}', array('as' => 'manager.user.getEditDummy', 'uses' => 'UserController@getEdit'));
    Route::post('manager/user/edit/{id}', array('as' => 'manager.user.postEdit', 'uses' => 'UserController@postEdit'));
    Route::post('manager/user/delete', array('as' => 'manager.user.postDelete', 'uses' => 'UserController@postDelete'));
    Route::get('manager/users', array('as' => 'manager.user.view', 'uses' => 'UserController@getView'));
    Route::post('manager/users', array('as' => 'manager.user.postView', 'uses' => 'UserController@postView'));

    //support
    Route::get('manager/support/ticket/new', array('as' => 'manager.support.getNewTicket', 'uses' => 'SupportController@getNewTicket'));
    Route::post('manager/support/ticket/new', array('as' => 'manager.support.postNewTicket', 'uses' => 'SupportController@postNewTicket'));
    Route::get('manager/support/ticket/{id}', array('as' => 'manager.support.getTickets', 'uses' => 'SupportController@getTickets'));
    Route::post('manager/support/ticket/{id}', array('as' => 'manager.support.postAllTickets', 'uses' => 'SupportController@postTickets'));
    Route::get('manager/support/ticket/view/{id}', array('as' => 'manager.support.getViewTicket', 'uses' => 'SupportController@getViewTicket'));
    Route::post('manager/support/ticket/view/{id}', array('as' => 'manager.support.postViewTicket', 'uses' => 'SupportController@postViewTicket'));
    Route::get('manager/support/mail', array('as' => 'manager.support.getMailBlast', 'uses' => 'SupportController@getMailBlast'));
    Route::post('manager/support/mail', array('as' => 'manager.support.postMailBlast', 'uses' => 'SupportController@postMailBlast'));
});

Route::group(array('namespace' => 'Admin','middleware' => 'auth'), function()
{
    Route::match(['get', 'post'],'admin/login', array('as' => 'admin.login.index', 'uses' => 'LoginController@index'));

    //dashboards
    Route::get('admin/dashboard', array('as' => 'admin.dashboard.index', 'uses' => 'DashboardController@index'));

    //settings
    Route::get('admin/settings', array('as' => 'admin.dashboard.getSettings', 'uses' => 'DashboardController@getSettings'));
    Route::post('admin/settings', array('as' => 'admin.dashboard.postSettings', 'uses' => 'DashboardController@postSettings'));

    //Billing
    Route::get('admin/billing/payments', array('as' => 'admin.billing.getPayments', 'uses' => 'BillingController@getPayments'));
    Route::post('admin/billing/payments', array('as' => 'admin.billing.postPayments', 'uses' => 'BillingController@postPayments'));


    //access point
    Route::get('admin/access-point/register', array('as' => 'admin.accessPoint.getRegister', 'uses' => 'AccessPointController@getRegister'));
    Route::post('admin/access-point/register', array('as' => 'admin.accessPoint.postRegister', 'uses' => 'AccessPointController@postRegister'));
    Route::get('admin/access-point', array('as' => 'admin.accessPoint.getList', 'uses' => 'AccessPointController@getList'));
    Route::post('admin/access-point/delete', array('as' => 'admin.accessPoint.postDelete', 'uses' => 'AccessPointController@postDelete'));
    Route::get('admin/access-point/update/{id}', array('as' => 'admin.accessPoint.getUpdate', 'uses' => 'AccessPointController@getUpdate'));
    Route::post('admin/access-point/update/{id}', array('as' => 'admin.accessPoint.postUpdate', 'uses' => 'AccessPointController@postUpdate'));

app/Models/Invoice.php
<?php namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Invoice extends Model {


    /**
     * @return \Illuminate\Database\Eloquent\Relations\MorphTo
     */
    public function packageable()
    {
        return $this->morphTo();
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo('App\Models\User','user_id','id');
    }

    /**
     * @param $value
     * @return string
     */
    public function getCreatedAtAttribute($value)
    {
        return Carbon::parse($value)->format('d M Y h:i a');
    }

    /**
     * @param $value
     * @return float
     */
    public function getPaidAmountAttribute($value)
    {
        return number_format($value,2);
    }

}

app/Http/Controllers/Admin/BillingController.php
<?php namespace App\Http\Controllers\Admin;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\Invoice;
use Illuminate\Http\Request;
use Billing;

class BillingController extends Controller {

    /**
     * @return \Illuminate\View\View
     */
    public function getPayments()
    {
        return view('admin.billing.invoices')
            ->with('billing',Billing::getInstance())
            ->with('invoices',Invoice::where('packageable_type',"App\\Models\\WifiManagerPackages")->latest()->paginate(10));
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function postPayments(Request $request)
    {
        if($request->has('addPayment')){
            //add payment
            try {
                //get user of invoice
                Billing::setUser(Invoice::find($request->get('invoice_id'))->user);
                Billing::verifyGatewayPayment($request, 'manual');
                //success
                $data = ['alert'=>'success','msg'=>'Payment added to invoice!'];
            } catch (\Exception $e) {
                //error
                //dd($e->getTraceAsString());
                $data = ['alert'=>'danger','msg'=>$e->getMessage()];
            }

        }
        else{
            //cancel invoice
            $data = ['alert'=>'warning','msg'=>'Invoice cancelled!'];
            Billing::cancelInvoice($request->get('invoice_id'));
        }
        return redirect()->route('admin.billing.getPayments')->with('data',$data);
    }

}

app/Http/Controllers/Admin/ManagerController.php
<?php namespace App\Http\Controllers\Admin;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Models\Profile;
use App\Models\Role;
use App\Models\User;
use App\Models\WifiManagerPackages;
use DB;
use Illuminate\Http\Request;
use SSH;
use Session;
use JavaScript;
use Billing;
use Radius;

class ManagerController extends Controller
{

    /**
     * @return \Illuminate\View\View
     */
    public function getRegister()
    {
        $packages = WifiManagerPackages::all();
        //$data = array('alert'=>'info','msg'=>'The Manager has been registered!','title'=>'Success!');
        //Session::flash('data',$data);
        return view('admin.manager.register')->with('packages',$packages->toArray());
    }

    /**
     * @param Request $request
     * @return $this
     */
    public function postRegister(Request $request)
    {
        //dd(intval($request->get('package_id')));
        //User::whereUsername($request->input('username'))->delete();
        $input = $request->all();
        $user = User::create($input);
        $user->username = $input['username'];
        $user->email = $input['email'];
        $user->password = bcrypt($input['password']);

        //$profile = Profile::create($input);
        $user->profile()->create($input);
        $user->save();

        //only package_id > 0
        if(intval($input['package_id']) )
            Billing::setUser($user)->subscribe($request->get('package_id'),'App\Models\WifiManagerPackages')->invoice();


        //attach role
        $role = Role::whereName('wifimanager')->first();
        $user->attachRole($role);

        $data = array('alert'=>'info','msg'=>'The Manager has been registered!','title'=>'Success!');
        return redirect()->route('admin.manager.getRegister')->with('data',$data);

    }

    /**
     * List of Wi-Fi Manager
     * @return \Illuminate\View\View
     */
    public function getView()
    {
        $managers = User::with(['subscription','roles'])
            ->whereHas('roles',function($q){
                $q->where('name','wifimanager');
            })
            ->paginate(10);
        $package = new WifiManagerPackages();
        return view('admin.manager.view')
            ->with('managers',$managers)
            ->with('package',$package);
    }

    /**
     * Delete manager
     * @param Request $request
     * @return string
     * @throws \Exception
     */
    public function postDelete(Request $request)
    {
        try{
            $user = User::find($request->input('user_id'));
            //find the users under the manager
            $end_users = DB::table('manager')->where('manager_id',$user->id)->get();
            //delete all the users
            foreach($end_users as $u){
                $end_user = User::find($u->user_id);
                Radius::setUsername($end_user->username)->deleteAll();
                $end_user->delete();
            }
            $user->delete();
            return "OK";
        }
        catch(\Exception $e){
            return $e->getMessage()."\n".$e->getTraceAsString();
        }
    }

    public function getEdit(Request $request,$id)
    {
        $user = User::with(['subscription','profile'])->find($id)->toArray();
        $packages = WifiManagerPackages::all();
        JavaScript::put([
            'user_id' => $id,
            'package' => $user['subscription']
        ]);
        //dd($user);
        return view('admin.manager.edit')
            ->with('user',$user)
            ->with('packages',$packages->toArray());
    }

    public function postEdit(Request $request,$id)
    {
        $input = $request->all();
        $user = User::find($id);
        if($request->has('update_profile'))
        {
            //dd($input);
            $user->update($input);
            $user->email = $input['email'];
            $profile = Profile::whereUserId($id)->first();
            $profile->update($input);
            $user->profile()->save($profile);
            $user->save();

            //only package_id > 0
            if(intval($input['package_id']))
                Billing::setUser($user)->subscribe($request->get('package_id'),'App\Models\WifiManagerPackages')->invoice();
            else
                Billing::setUser($user)->unsubscribe()->cancelInvoice();

            $data = array('alert'=>'info','msg'=>'The profile has been updated!','title'=>'Success!');
        }
        else if($request->has('update_password'))
        {
            $user->password = bcrypt($input['password']);
            $user->save();
            $data = array('alert'=>'info','msg'=>'The password has been updated!','title'=>'Success!');
        }
        else
        {
            $data = array('alert'=>'danger','msg'=>'Invalid form','title'=>'Error!');
        }

        return redirect()->route('admin.manager.getEdit',$id)->with('data',$data);
    }


}

resources/views/manager/billing/invoice.blade.php
@extends('manager.master')

@section('breadcrumb')
    <li><a href="#">Home</a></li>
    <li>Billing</li>
    <li class="active">Invoice</li>
@stop

@section('pageContentWrap')

    @if(Session::has('data'))
        <div class="row">
            <div class="col-md-12" style="padding: 15px;">
                <div class="alert alert-{{Session::get('data')['alert']}}" id="alert">
                    <button type="button" class="close" data-dismiss="alert">x</button>
                    <strong>{{Session::get('data')['title']}} </strong>
                    {{Session::get('data')['msg']}}
                </div>
            </div>
        </div>
    @endif


    <div class="row">
        <div class="col-md-12">

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><img width="32px" height="32px" src="{{URL::asset('img/icons/csv.png')}}" /><strong>Invoice</strong></h3>
                    <ul class="panel-controls">
                        <li style="margin-top:5px;margin-right:30px">
                            @if($billing->getInvoice()->status == "unpaid")
                                <span style="padding:5px;color:white;background-color: red">UNPAID</span>
                            @else
                                <span style="padding:5px;color:white;background-color: green">PAID</span>
                            @endif
                        </li>
                    </ul>
                </div>

                <div class="panel-body">

                    <div class="block">
                        <div class="col-md-8 col-md-offset-4">
                            <h3 >Please select your payment method</h3>
                        {!! Form::open(['method'=>'post','id'=>'form_subscribe','class'=>'form-inline']) !!}
                        <div class="form-group">
                            <div class="col-md-3">
                                <select id="payment_method" name="payment_method" class="form-control">
                                    <option value="paypal">Paypal / Credit Card</option>
                                    <option value="manual">Bank Transfer / Cash</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-3">
                                <select name="cycle" class="form-control">
                                    @if($billing->getInvoice()->packageable->monthly_price > 0)
                                        <option value="monthly_price">Monthly ({{$billing->getCurrency().$billing->getInvoice()->packageable->monthly_price}})</option>
                                    @endif
                                    @if($billing->getInvoice()->packageable->semi_annually_price > 0)
                                        <option value="semi_annually_price">Semi Annually ({{$billing->getCurrency().$billing->getInvoice()->packageable->semi_annually_price}})</option>
                                    @endif
                                    @if($billing->getInvoice()->packageable->annually_price > 0)
                                        <option value="annually_price">Annually ({{$billing->getCurrency().$billing->getInvoice()->packageable->annually_price}})</option>
                                    @endif
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-3">
                                <button id="button_pay" type="submit" class="btn btn-danger">Pay</button>
                            </div>
                        </div>
                        {!! Form::close() !!}
                            </div>
                    </div>




                    <!-- PayPal Logo -->
                    <table border="0" cellpadding="10" cellspacing="0" align="center">
                        <tr>
                            <td align="center"></td>
                        </tr>
                        <tr  id="row_paypal">
                            <td align="center">
                                <img src="https://www.paypalobjects.com/webstatic/mktg/logo/AM_SbyPP_mc_vs_dc_ae.jpg"
                                            border="0" alt="PayPal Acceptance Mark"></td>
                        </tr>
                        <tr style="display: none" id="row_manual">
                            <td align="center">
                                {!! config('services.manual.instructions') !!}
                            </td>
                        </tr>
                    </table>
                    <!-- PayPal Logo -->

                </div>

                <div class="panel-footer">
                </div>
            </div>

        </div>

    </div>

    <!-- MESSAGE BOX-->
    <div id="confirmBox">
    </div>


@stop


@section('thisPageJs')

    <script type='text/javascript' src='{{ URL::asset('js/plugins/icheck/icheck.min.js')}}'></script>
    <script type="text/javascript" src="{{ URL::asset('js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js')}}"></script>
    <script type="text/javascript" src="{{ URL::asset('js/plugins/scrolltotop/scrolltopcontrol.js')}}"></script>

    <script type="text/javascript" src="{{ URL::asset('js/plugins/bootstrap/bootstrap-file-input.js')}}"></script>

    <script type='text/javascript' src='{{ URL::asset('js/plugins/datatables/jquery.dataTables.min.js')}}'></script>

    <script type='text/javascript' src='{{ URL::asset('js/plugins/bootstrap/bootstrap-datepicker.js')}}'></script>
    <script type="text/javascript" src="{{ URL::asset('js/plugins/owl/owl.carousel.min.js')}}"></script>
    <script type="text/javascript" src="{{ URL::asset('js/custom.js')}}"></script>


    <script type="text/javascript" >

        //ajax
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        $(document).ready(function () {

            $('#payment_method').change(function(){
                payment_method = $(this).children(":selected").val();
                console.log(payment_method);
                if(payment_method == "manual"){
                    $("#button_pay").hide();
                    $("#row_paypal").hide();
                    $("#row_manual").show();
                }
                else{
                    $("#button_pay").show();
                    $("#row_paypal").show();
                    $("#row_manual").hide();
                }
            })

        });

    </script>


@stop

resources/views/manager/billing/invoices.blade.php
@extends('manager.master')

@section('breadcrumb')
    <li><a href="#">Home</a></li>
    <li>Billing</li>
    <li class="active">Invoices</li>
@stop

@section('pageContentWrap')

    @if(Session::has('data'))
        <div class="row">
            <div class="col-md-12" style="padding: 15px;">
                <div class="alert alert-{{Session::get('data')['alert']}}" id="alert">
                    <button type="button" class="close" data-dismiss="alert">x</button>
                    <strong>{{Session::get('data')['title']}} </strong>
                    {{Session::get('data')['msg']}}
                </div>
            </div>
        </div>
    @endif


    <div class="row">
        <div class="col-md-12">

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><img width="32px" height="32px" src="{{URL::asset('img/icons/invoice.png')}}" /><strong>Invoices</strong></h3>
                    <ul class="panel-controls">
                        <li><a href="#" class="panel-collapse"><span class="fa fa-angle-down"></span></a></li>
                    </ul>
                </div>

                <div class="panel-body">

                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-actions">
                            <thead>
                            <tr>
                                <th width="10">ID</th>
                                <th>Package Name</th>
                                <th>Package Descriptions</th>
                                <th>Amount Paid</th>
                                <th>Date</th>
                                <th>Status</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>

                            @foreach($invoices as $invoice)
                                <tr>
                                    <td>{{$invoice->id}}</td>
                                    <td>{{$invoice->packageable->name}}</td>
                                    <td>{{$invoice->packageable->descriptions}}</td>
                                    <td>
                                        @if($invoice->paid_amount > 0)
                                            {{$billing->getCurrency().$invoice->paid_amount}}
                                        @else
                                            ---
                                        @endif
                                    </td>
                                    <td>{{$invoice->created_at}}</td>
                                    <td>
                                        <span style="background-color:
                                        @if($invoice->status == "unpaid")
                                                red;
                                        @elseif($invoice->status == "paid")
                                                green;
                                        @else
                                                #BCC1C8;
                                        @endif
                                                color:white;padding: 4px;">
                                            {{$invoice->status}}
                                        </span>

                                    </td>
                                    <td>
                                        {!! Form::open(['method'=>'post','id'=>'form_invoice','class'=>'form_invoice_'.$invoice->id]) !!}
                                        <input type="hidden" name="invoice_id" value="{{$invoice->id}}">
                                        @if($invoice->status == "unpaid")
                                            <button type="button" onclick="window.location.href = '{{URL::route('manager.billing.getInvoice',$invoice->id)}}'" class="btn btn-info"><i class="fa fa-file-text-o"></i> View</button>
                                            <button name="cancel" value="1" class="btn btn-danger"><i class="fa fa-times-circle"></i> Cancel</button>
                                        @endif
                                        {!! Form::close() !!}
                                    </td>
                                </tr>
                            @endforeach

                            </tbody>
                        </table>
                        @if(count($invoices)>0)
                            {!!$invoices->render()!!}
                        @endif
                    </div>
                </div>

                <div class="panel-footer">
                </div>
            </div>

        </div>

    </div>

    <!-- MESSAGE BOX-->
    <div id="confirmBox">
    </div>


@stop


@section('thisPageJs')

    <script type='text/javascript' src='{{ URL::asset('js/plugins/icheck/icheck.min.js')}}'></script>
    <script type="text/javascript" src="{{ URL::asset('js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js')}}"></script>
    <script type="text/javascript" src="{{ URL::asset('js/plugins/scrolltotop/scrolltopcontrol.js')}}"></script>

    <script type="text/javascript" src="{{ URL::asset('js/plugins/bootstrap/bootstrap-file-input.js')}}"></script>

    <script type='text/javascript' src='{{ URL::asset('js/plugins/datatables/jquery.dataTables.min.js')}}'></script>

    <script type='text/javascript' src='{{ URL::asset('js/plugins/bootstrap/bootstrap-datepicker.js')}}'></script>
    <script type="text/javascript" src="{{ URL::asset('js/plugins/owl/owl.carousel.min.js')}}"></script>
    <script type="text/javascript" src="{{ URL::asset('js/custom.js')}}"></script>


    <script type="text/javascript" >

        //ajax
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        $(document).ready(function () {

            var formClass;

            $('#form_invoice').submit(function (event) {
                formClass = $(this).attr('class');
                console.log(formClass);
                confirmBox("Confirmation","Are you sure to cancel the invoice?","#confirmBox",null,null,function(){
                    //console.log(formInstance.find('input[name=invoice_id]').val());
                    console.log(formClass);
                    $('.'+formClass).unbind('submit').submit();
                });
                event.preventDefault();
            });

        });

    </script>


@stop